name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'     # uses the major.minor in go.mod
          cache: true                   # re-uses module & build caches

      - name: Unit tests
        run: go test ./...

      - name: Static analysis (golangci-lint)
        uses: golangci/golangci-lint-action@v3  # official action  [oai_citation:0‡GitHub](https://github.com/golangci/golangci-lint-action?utm_source=chatgpt.com)
        with:
          version: v1.59
          args: --timeout=3m