name: Release
on:
  push:
    tags: ['v*']          # v1.2.3 → release

permissions:
  contents: write         # allow create/upload release assets

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Required for GoReleaser to work properly
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6  # Updated to v6
        with:
          distribution: goreleaser
          version: "~> v2"    # Use v2 with proper semver constraint
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}